version: "3"

services:
  NetWatchSSHAttackPod:
    image: netwatchteam/netwatch_ssh-attackpod:latest
    container_name: netwatch_ssh-attackpod 
    build:
      context: src
    environment:
      NETWATCH_COLLECTOR_AUTHORIZATION: ${NETWATCH_COLLECTOR_AUTHORIZATION}
      NETWATCH_COLLECTOR_URL: "https://api.netwatch.team"
      NETWATCH_TEST_MODE: ${NETWATCH_TEST_MODE:-false}
    restart: unless-stopped
    ports:
      - "${NETWATCH_PORT:-22}:2222"
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 750M
        reservations:
          cpus: "0.25"
          memory: 200M
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "2"
